project_id = "jdukmuskbpalfqmjelnl"

[functions.send-invitation]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false

[functions.hubspot-sync]
verify_jwt = true

[functions.calculate-metrics]
verify_jwt = false

[functions.fetch-meta-ads]
verify_jwt = true

[functions.fetch-google-ads]
verify_jwt = true
